/* eslint-disable @typescript-eslint/no-var-requires */
export const GLOBAL_IMAGES = {
  logo: require('./imports/logo.png'),
  appAvtar: require('./imports/app-img.png'),
  banner1: require('./imports/banner/img-1.jpg'),
};

export const GLOBAL_ICON = {
  ambulance: require('./imports/icons/ambulance.png'),
  arrow: require('./imports/icons/arrow.png'),
  bell: require('./imports/icons/bell.png'),
  bills: require('./imports/icons/bills.png'),
  boyReading: require('./imports/icons/boy-reading.png'),
  call: require('./imports/icons/call.png'),
  chevronDown: require('./imports/icons/chevron-down.png'),
  chevronLeft: require('./imports/icons/chevron-left.png'),
  chevronRight: require('./imports/icons/chevron-right.png'),
  chevronUp: require('./imports/icons/chevron-up.png'),
  community: require('./imports/icons/community.png'),
  creamation: require('./imports/icons/creamation.png'),
  cross: require('./imports/icons/cross.png'),
  downPayment: require('./imports/icons/down-payment.png'),
  emergancy: require('./imports/icons/emergancy.png'),
  event: require('./imports/icons/event.png'),
  fillCircle: require('./imports/icons/fill-circle.png'),
  finanacial: require('./imports/icons/finanacial.png'),
  firedep: require('./imports/icons/firedep.png'),
  foodPantries: require('./imports/icons/food-pantries.png'),
  foodResources: require('./imports/icons/food-resources.png'),
  funding: require('./imports/icons/fuding.png'),
  globe: require('./imports/icons/globe.png'),
  home: require('./imports/icons/home.png'),
  homeLess: require('./imports/icons/homeLess.png'),
  homeRepair: require('./imports/icons/home-repair.png'),
  location: require('./imports/icons/location.png'),
  meeting: require('./imports/icons/meeting.png'),
  menu: require('./imports/icons/menu.png'),
  mobilePantries: require('./imports/icons/mobile-pantries.png'),
  notification: require('./imports/icons/notification.png'),
  outreachLocation: require('./imports/icons/outreach-location.png'),
  partners: require('./imports/icons/partners.png'),
  police: require('./imports/icons/police.png'),
  publicSafety: require('./imports/icons/public-safety.png'),
  rental: require('./imports/icons/rental.png'),
  setting: require('./imports/icons/setting.png'),
  shelter: require('./imports/icons/shelter.png'),
  suicide: require('./imports/icons/suicide.png'),
  tick: require('./imports/icons/tick.png'),
  training: require('./imports/icons/training.png'),
  visit: require('./imports/icons/visit.png'),
  veteran: require('./imports/icons/veteran.png'),
  weather: require('./imports/icons/weather.png'),
  mapMarker: require('./imports/icons/map_marker.png'),
  noInternet: require('./imports/no-internet.png'),
};
